In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
A = np.random.randint(0,100, size=(10,5,4))
A

array([[[83, 91, 99, 25],
        [29, 10, 82, 89],
        [10, 19, 91, 58],
        [93, 61, 50, 26],
        [ 2, 96, 74, 98]],

       [[84,  8, 97, 51],
        [42, 44,  3, 90],
        [80, 98, 73, 98],
        [19, 33, 20, 47],
        [39, 16, 48, 62]],

       [[74, 16, 76, 47],
        [11, 82, 29, 85],
        [23, 44, 67, 25],
        [33, 81, 51, 18],
        [ 9, 46, 51, 78]],

       [[ 5, 61, 52, 23],
        [14, 62, 14, 26],
        [23, 69, 12, 85],
        [92, 68, 49, 20],
        [24, 95, 10,  7]],

       [[68, 48, 42, 35],
        [76, 52, 13, 79],
        [86, 24, 83, 54],
        [14,  2, 13, 59],
        [84, 66, 45, 89]],

       [[53,  6, 38,  4],
        [53, 15, 96, 75],
        [82, 97, 14, 97],
        [87, 37,  9, 16],
        [68, 80, 31, 95]],

       [[ 0, 61, 74, 64],
        [65, 82, 52,  3],
        [48, 83, 46, 68],
        [14, 31,  5, 98],
        [86, 84, 62, 54]],

       [[87, 87, 12, 97],
        [54, 57, 48, 40],
        [92, 69, 47,  2]

In [7]:
A.flatten().reshape(5,8)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 0,  4,  8, 12, 16, 20, 24, 28]])

In [37]:
N_particles = 20

In [38]:
A = np.array([i for i in range(60)]).reshape(N_particles,3)

A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [39]:
where_list = [i for i,m in enumerate((True,True,False,True)) if not m]
where_list

[2]

In [40]:
for i,m in enumerate(where_list):
    if m > A.shape[1]:
        where_list[i] = A.shape[1]

In [41]:
where_list

[2]

In [42]:
np.insert( A, where_list, np.zeros((N_particles,1)), axis = 1) 

array([[ 0,  1,  0,  2],
       [ 3,  4,  0,  5],
       [ 6,  7,  0,  8],
       [ 9, 10,  0, 11],
       [12, 13,  0, 14],
       [15, 16,  0, 17],
       [18, 19,  0, 20],
       [21, 22,  0, 23],
       [24, 25,  0, 26],
       [27, 28,  0, 29],
       [30, 31,  0, 32],
       [33, 34,  0, 35],
       [36, 37,  0, 38],
       [39, 40,  0, 41],
       [42, 43,  0, 44],
       [45, 46,  0, 47],
       [48, 49,  0, 50],
       [51, 52,  0, 53],
       [54, 55,  0, 56],
       [57, 58,  0, 59]])

In [43]:
if (False):
    print("Nope")